### ISSUE TITLE
Allow float alongside double in query response fields

### ISSUE THREAD

**Issue by molinaro-m** [ivoa-std/ObjVisSAP#11]
Section 4.1.1, listing the output fields for successful queries, sets to **double** all floating numeric fields
(this is also reflected in the summary table in Appendix A).

Could this be relaxed to allow both **float** and **double** values as acceptable (unless specific requirements exist, but that should happen for specific reasons on single fields)?

**Comment by jesusjuansalgado** [comment]
Changed
