### ISSUE TITLE
Add "accuracy" information as part of the response

### ISSUE THREAD

**Issue by aibaiba** [ivoa-std/ObjVisSAP#9]
Depending on the astronomical observatory, the accuracy of  the target visibility may depend how long into the future you want to have the visibility. 
Therefore, it will be nice to have in the service response an extra field called "accuracy", where the facilities will reflect if the visibility period has high. low or medium.

**Comment by jesusjuansalgado** [comment]
Solved by branch issue-solving-11-9-7
